# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-realty`

cian-codegen version: 1.9.0

"""
from dataclasses import dataclass
from typing import Optional


@dataclass
class ApiAutocompleteUndeground:
    region_id: int
    """id локации, где ищем метро"""
    all: Optional[bool] = None
    """не ограничивать количество предлагаемых элементов в выдаче, по умолчанию, отдаем первые 15 элементов"""
    lat: Optional[float] = None
    """широта выбранного адреса (если есть), для расчета времени, сколько идти/ехать в транспорте до метро"""
    lng: Optional[float] = None
    """долгота выбранного адреса (если есть), для расчета времени, сколько идти/ехать в транспорте до метро"""
    q: Optional[str] = None
    """текст из поля ввода"""
