# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-geoapi`

cian-codegen version: 1.12.2

"""
from typing import List

from cian_http.api_client import Api

from . import entities


_api = Api(microservice_name='monolith-cian-geoapi')
v1_get_districts_by_child = _api.make_client(
    path='/v1/get-districts-by-child/',
    method='GET',
    handle_http_exceptions=True,
    request_schema=entities.V1GetDistrictsByChild,
    response_schema=List[entities.GetDistrictsResponse]
)

v2_geocode = _api.make_client(
    path='/v2/geocode/',
    method='POST',
    handle_http_exceptions=True,
    request_schema=entities.GeoCodedRequest,
    response_schema=entities.GeoCodedResponse
)

v2_undergrounds_get_all = _api.make_client(
    path='/v2/undergrounds/get-all/',
    method='GET',
    handle_http_exceptions=True,
    request_schema=entities.V2UndergroundsGetAll,
    response_schema=List[entities.UndergroundModelV2]
)
