# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-geoapi`

cian-codegen version: 1.12.2

"""
from dataclasses import dataclass
from typing import Optional


@dataclass
class DistrictDirection:
    """Направление района (в основном, используется для округов Москвы)"""
    code: Optional[str] = None
    """Код"""
    name: Optional[str] = None
    """Название"""
