# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-geoapi`

cian-codegen version: 1.12.2

"""
from dataclasses import dataclass
from typing import Optional


@dataclass
class GeoCodedRequest:
    address: Optional[str] = None
    """Адрес"""
    kind: Optional[str] = None
    """Вид топонима (обязательный параметр)."""
    lat: Optional[float] = None
    """Широта."""
    lng: Optional[float] = None
    """Долгота."""
