# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-geoapi`

cian-codegen version: 1.16.3

"""
from dataclasses import dataclass
from typing import Optional


@dataclass
class LocationResponse:
    id: Optional[int] = None
    """Id локации."""
    name: Optional[str] = None
    """Название."""
    oblast_id: Optional[int] = None
    """Id области локации"""
    time_zone: Optional[int] = None
    """TimeZone"""
