# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-geoapi`

cian-codegen version: 1.12.2

"""
from dataclasses import dataclass
from typing import Optional


@dataclass
class UndergroundEntrance:
    """Вход в метро"""

    id: Optional[int] = None
    """Id входа в метро"""
    lat: Optional[float] = None
    """Широта"""
    lng: Optional[float] = None
    """Долгота"""
    name: Optional[str] = None
    """Название входа в метро"""
