# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-geoapi`

cian-codegen version: 1.12.2

"""
from dataclasses import dataclass
from typing import Optional

from cian_enum import NoFormat, StrEnum


class GeoType(StrEnum):
    __value_format__ = NoFormat
    country = 'Country'
    """Страна"""
    location = 'Location'
    """Населённый пункт"""
    street = 'Street'
    """Улица"""
    road = 'Road'
    """Шоссе"""
    district = 'District'
    """Район"""
    underground = 'Underground'
    """Метро"""
    house = 'House'
    """Дом"""


@dataclass
class V1GetDistrictsByChild:
    geo_object_type: Optional[GeoType] = None
    """Тип"""
    id: Optional[int] = None
    """Ид"""
