name = "external-offers"
team = "b2b"

[runtime]
name = "python"
version = "3.8"

[[dependency]]
type = "postgres"
alias = "external_offers"

[[dependency]]
type = "rabbitmq"

[[dependency]]
type = "kafka"
alias = "default"

[job.web]
type = "web"

[job.save-parsed-offers]
type = "consumer"
command = "save-parsed-offers"

[job.create-offers-for-call-from-parsed]
type = "cron"
command = "create-offers-for-call"
cron = "0 2 * * *"

[job.sync-event-log-with-kafka-analytics]
type = "manage"
command = "sync-event-log-with-kafka-analytics"

[job.send-latest-parsed-offers-timestamp-diff-to-graphite]
type = "cron"
command = "send-latest-parsed-offers-timestamp-diff-to-graphite"
cron = "*/15 * * * *"