name = "external-offers"
team = "b2b"
[runtime]
name = "python"
version = "3.9"
features.preset = "v2"
features.disabled = ["mypy_ci_fail"]

[[dependency]]
type = "postgres"
alias = "external_offers"

[[dependency]]
type = "rabbitmq"

[[dependency]]
type = "redis"

[[dependency]]
type = "kafka"
alias = "default"

[job.web]
type = "web"

[job.save-parsed-offers]
type = "consumer"
command = "save-parsed-offers"

[job.save-parsed-offers.prod]
cpu = 0.4
memory = 512

[job.send-parsed-offers]
type = "consumer"
command = "send-parsed-offers"

[job.create-offers-for-call-from-parsed]
type = "cron"
command = "create-offers-for-call"
cron = "0 2 * * *"

[job.send-latest-parsed-offers-timestamp-diff-to-graphite]
type = "cron"
command = "send-latest-parsed-offers-timestamp-diff-to-graphite"
cron = "0 */2 * * *"

[job.clear-outdated-offers]
type = "cron"
command = "clear-outdated-offers-cron"
cron = "0 0 * * *"

[job.send-parsed-offers-to-kafka-cron]
type = "cron"
command = "send-parsed-offers-to-kafka-cron"
cron = "0 7 * * *"

[job.send-offers-for-call-to-kafka-cron]
type = "cron"
command = "send-offers-for-call-to-kafka-cron"
cron = "0 7 * * *"

[job.send-waiting-offers-and-clients-amount-to-grafana-cron]
type = "cron"
command = "send-waiting-offers-and-clients-amount-to-grafana-cron"
cron = "0 8 * * *"

[job.send-non-waiting-offers-and-clients-amount-to-grafana-cron]
type = "cron"
command = "send-non-waiting-offers-and-clients-amount-to-grafana-cron"
cron = "0 21 * * *"
