name = "external-offers"
team = "b2b"

[runtime]
name = "python"
version = "3.8"

[[dependency]]
type = "postgres"
alias = "external_offers"

[[dependency]]
type = "rabbitmq"

[[dependency]]
type = "kafka"
alias = "default"

[job.web]
type = "web"

[job.save-parsed-offers]
type = "consumer"
command = "save-parsed-offers"
