from external_offers.repositories.postgresql.clients import get_client_by_operator
from external_offers.repositories.postgresql.offers import get_offers_in_progress_by_operator
from external_offers.repositories.postgresql.parsed_offers import save_parsed_offer
