# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client moderation-confidence-index`

cian-codegen version: 2.1.0

"""
from dataclasses import dataclass
from datetime import datetime as _datetime
from typing import Optional


@dataclass
class GetOperatorCallsFilter:
    """Фильтр звонков операторов"""

    duration_max: Optional[int] = None
    """Фильтр по длительности "по\""""
    duration_min: Optional[int] = None
    """Фильтр по длительности "от\""""
    is_connected: Optional[bool] = None
    """Статус соединение устанолвено"""
    is_incoming: Optional[bool] = None
    """Признак, что это входящий вызов"""
    operator_id: Optional[int] = None
    """Идентификатор оператора"""
    page: Optional[int] = None
    """Номер страницы"""
    page_size: Optional[int] = None
    """Размер страницы"""
    phone_from: Optional[str] = None
    """С какого телефона"""
    phone_to: Optional[str] = None
    """На какой телефон"""
    task_key: Optional[str] = None
    """Ключ таски"""
    team: Optional[str] = None
    """Команда"""
    time_from: Optional[_datetime] = None
    """Время с"""
    time_to: Optional[_datetime] = None
    """Время по"""
