# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client moderation-confidence-index`

cian-codegen version: 2.1.0

"""
from dataclasses import dataclass
from datetime import datetime as _datetime
from typing import Optional

from cian_enum import NoFormat, StrEnum


class Status(StrEnum):
    __value_format__ = NoFormat
    new = 'new'
    """Новый"""
    in_progress = 'inProgress'
    """В процессе"""
    completed = 'completed'
    """Завершён"""
    error = 'error'
    """Ошибка"""


@dataclass
class GetCsvReportStatusResponseModel:
    """Модель отчёта"""

    changed_time: Optional[_datetime] = None
    """Время изменения"""
    created_time: Optional[_datetime] = None
    """Время создания"""
    status: Optional[Status] = None
    """Статус CSV-отчёта"""
    url: Optional[str] = None
    """Урл на скачивание"""
