# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client moderation-confidence-index`

cian-codegen version: 2.1.0

"""
from dataclasses import dataclass
from datetime import datetime as _datetime
from typing import Optional
from uuid import UUID

from cian_enum import NoFormat, StrEnum


class Status(StrEnum):
    __value_format__ = NoFormat
    new = 'new'
    """Новый звонок"""
    connected = 'connected'
    """Подключён"""
    not_connected = 'notConnected'
    """Не подключён"""


@dataclass
class OperatorCallModel:
    beep_duration: Optional[int] = None
    """Длительность гудков"""
    call_id: Optional[UUID] = None
    """Идентификатор звонка"""
    created_time: Optional[_datetime] = None
    """Время начала звонка"""
    duration: Optional[int] = None
    """Теелфон на который звоним"""
    is_incoming: Optional[bool] = None
    """Входящий звонок"""
    mp3_url: Optional[str] = None
    """Урл до Mp3"""
    operator_id: Optional[int] = None
    """Идентификатор оператора"""
    phone_from: Optional[str] = None
    """Телефон с которого звоним"""
    phone_to: Optional[str] = None
    """Теелфон на который звоним"""
    status: Optional[Status] = None
    """Статус звонка через веб"""
    task_key: Optional[str] = None
    """Ключ таски"""
    team: Optional[str] = None
    """Команда"""
