
ALTER TABLE offers_for_call ADD COLUMN is_test BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE clients ADD COLUMN is_test BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE parsed_offers ADD COLUMN is_test BOOLEAN NOT NULL DEFAULT FALSE;
