# pylint: skip-file
# isort:skip_file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-service`

cian-codegen version: 1.12.2

"""
from .auction_points_strategy_model import AuctionPointsStrategyModel
from .bonus_on_payment_strategy_model import BonusOnPaymentStrategyModel
from .promocode_response import PromocodeResponse
from .create_promocode_group_response import CreatePromocodeGroupResponse
from .discaunt_by_tariff_strategy_model import DiscauntByTariffStrategyModel
from .money_strategy_model import MoneyStrategyModel
from .promo_code_group_model import PromoCodeGroupModel
from .service_package_strategy_item_model import ServicePackageStrategyItemModel
from .service_package_strategy_model import ServicePackageStrategyModel
from .promo_code_group_detail_model import PromoCodeGroupDetailModel
