# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-service`

cian-codegen version: 1.12.2

"""
from dataclasses import dataclass
from typing import List

from .promocode_response import PromocodeResponse


@dataclass
class CreatePromocodeGroupResponse:
    """Результат создания группы промокодов."""

    id: int
    """Id группы промокодов."""
    promocodes: List[PromocodeResponse]
    """Список промокодов группы."""
