# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-service`

cian-codegen version: 1.12.2

"""
from dataclasses import dataclass
from datetime import datetime as _datetime
from typing import Optional

from cian_enum import NoFormat, StrEnum


class Source(StrEnum):
    __value_format__ = NoFormat
    other = 'Other'
    """Другой"""
    certificate_for_partner = 'CertificateForPartner'
    """Сертификат партнеру"""
    certificate_for_conference = 'CertificateForConference'
    """Сертификат на мероприятие/конференцию"""
    certificate_for_webinar = 'CertificateForWebinar'
    """Сертификат на вебинар"""
    newcontact = 'Newcontact'
    """Контакт центр Ньюконтакт"""
    tango_telecom = 'TangoTelecom'
    """Контакт центр Танго Телеком"""
    current_clients = 'CurrentClients'
    """Текущие клиенты Cian.ru"""
    left_clients = 'LeftClients'
    """Ушедшие клиенты Cian.ru"""


class SubdivisionType(StrEnum):
    __value_format__ = NoFormat
    sales = 'Sales'
    """Отдел продаж"""
    marketing = 'Marketing'
    """Маркетинг"""
    customer_service = 'CustomerService'
    """КС"""
    testing_group = 'TestingGroup'
    """Группа тестирования"""


class Type(StrEnum):
    __value_format__ = NoFormat
    money = 'Money'
    """Бонусные деньги"""
    discaunt_by_tariff = 'DiscauntByTariff'
    """Скидка на тариф"""
    service_package = 'ServicePackage'
    """Пакеты размещений"""
    bonus_on_payment = 'BonusOnPayment'
    """Бонус за пополнение кошелька"""
    auction_points = 'AuctionPoints'
    """Баллы на аукцион"""


@dataclass
class PromoCodeGroupModel:
    """Модель группы промокодов."""

    available_to: _datetime
    """Доступна по"""
    for_specific_user_ids: bool
    """Для конкретных пользователей."""
    name: str
    """Название группы"""
    source: Source
    """Источник"""
    subdivision_type: SubdivisionType
    """Подразделение пользователя"""
    type: Type
    """Тип промо группы"""
    allow_add_promo_codes: Optional[bool] = None
    """Можно ли добавить ещё промокод для этой группы"""
    available_from: Optional[_datetime] = None
    """Доступна с"""
    cian_user_ids: Optional[str] = None
    """Список пользоватей, для которых нужно сгенерировать промокоды."""
    promo_codes_count: Optional[int] = None
    """Количество сгенерированных промокодов"""
    user_min_register_date: Optional[_datetime] = None
    """Минимальная дата регистрации пользователя."""
