# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-service`

cian-codegen version: 1.7.1

"""
from dataclasses import dataclass
from typing import Optional

from .auction_points_strategy_model import AuctionPointsStrategyModel
from .bonus_on_payment_strategy_model import BonusOnPaymentStrategyModel
from .discaunt_by_tariff_strategy_model import DiscauntByTariffStrategyModel
from .money_strategy_model import MoneyStrategyModel
from .promo_code_group_model import PromoCodeGroupModel
from .service_package_strategy_model import ServicePackageStrategyModel


@dataclass
class PromoCodeGroupDetailModel:
    auction_points_strategy: Optional[AuctionPointsStrategyModel] = None
    """Модель для баллов на аукцион"""
    bonus_on_payment_strategy: Optional[BonusOnPaymentStrategyModel] = None
    """Модель для промокода на бонус на пополнение"""
    discaunt_by_tariff_strategy: Optional[DiscauntByTariffStrategyModel] = None
    """Модель для скидки на активацию тарифа"""
    money_strategy: Optional[MoneyStrategyModel] = None
    """Модель для бонусных кодов на деньги"""
    promo_code_group_model: Optional[PromoCodeGroupModel] = None
    """Модель группы промокодов"""
    service_package_strategy: Optional[ServicePackageStrategyModel] = None
    """Модель для пакетов продвижения"""
