# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-service`

cian-codegen version: 1.7.1

"""
from dataclasses import dataclass
from typing import Optional

from .select_list_group import SelectListGroup


@dataclass
class SelectListItem:
    disabled: Optional[bool] = None
    group: Optional[SelectListGroup] = None
    selected: Optional[bool] = None
    text: Optional[str] = None
    value: Optional[str] = None
