# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-service`

cian-codegen version: 1.7.1

"""
from dataclasses import dataclass
from typing import List, Optional

from cian_enum import NoFormat, StrEnum

from .service_package_strategy_item_model import ServicePackageStrategyItemModel


class Type(StrEnum):
    __value_format__ = NoFormat
    slot = 'slot'
    """Слоты - переиспользуемые слоты в рамках срока действия пакета"""
    publication = 'publication'
    """Публикации - ограниченное количество публикаций объявлений за счет пакета"""


@dataclass
class ServicePackageStrategyModel:
    """Пакет по объёму."""

    is_paid: bool
    """true, если платный."""
    items: List[ServicePackageStrategyItemModel]
    """Список пакетов для активации."""
    type: Type
    """Тип пакета"""
    activation_price: Optional[float] = None
    """Стоимость активации промокода.<br />null, если бесплатно."""
    activations_count: Optional[int] = None
    """Количество активаций.<br />null, если бесконечно."""
    auto_activate_for_manual_announcements: Optional[bool] = None
    """Автоматическое применение к ручным объявлениям"""
