# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-realty`

cian-codegen version: 1.9.0

"""
from typing import List

from cian_http.api_client import Api

from . import entities


_api = Api(microservice_name='monolith-cian-realty')
api_autocomplete_undeground = _api.make_client(
    path='/api/autocomplete-undeground/',
    method='GET',
    handle_http_exceptions=True,
    request_schema=entities.ApiAutocompleteUndeground,
    response_schema=List[entities.AutocompleteSubway],
)
