# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client sms`

cian-codegen version: 1.15.0

"""
from cian_http.api_client import Api

from . import entities

_api = Api(microservice_name='sms')
v2_send_sms = _api.make_client(
    path='/v2/send-sms/',
    method='POST',
    handle_http_exceptions=True,
    request_schema=entities.SendSmsRequestV2,
    response_schema=entities.SendSmsResponseV2,
)
