# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client users`

cian-codegen version: 1.9.0

"""
from ._repo import v1_register_user_by_phone, v2_get_users_by_phone
