# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client users`

cian-codegen version: 1.16.5

"""
from cian_http.api_client import Api

from . import entities


_api = Api(microservice_name='users')
v1_get_user_roles = _api.make_client(
    path='/v1/get-user-roles/',
    method='GET',
    handle_http_exceptions=True,
    request_schema=entities.V1GetUserRoles,
    response_schema=entities.GetUserRolesResponse,
)
v1_register_user_by_phone = _api.make_client(
    path='/v1/register-user-by-phone/',
    method='POST',
    handle_http_exceptions=True,
    request_schema=entities.RegisterUserByPhoneRequest,
    response_schema=entities.RegisterUserByPhoneResponse,
)
v2_get_users_by_phone = _api.make_client(
    path='/v2/get-users-by-phone/',
    method='GET',
    handle_http_exceptions=True,
    request_schema=entities.V2GetUsersByPhone,
    response_schema=entities.GetUsersByPhoneResponseV2,
)
