# pylint: skip-file
# isort:skip_file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-profileapi`

cian-codegen version: 1.7.1

"""
from .apply_parameters import ApplyParameters
