# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-profileapi`

cian-codegen version: 1.14.2

"""
from dataclasses import dataclass
from typing import Optional


@dataclass
class ApplyParameters:
    cian_user_id: Optional[int] = None
    """Ключ пользователя"""
    promo_code: Optional[str] = None
    """Промокод"""
