# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-profileapi`

cian-codegen version: 1.14.2

"""
from dataclasses import dataclass
from datetime import datetime as _datetime
from typing import Optional


@dataclass
class UserSanctionItem:
    sanction_end: Optional[_datetime] = None
    sanction_id: Optional[int] = None
    sanction_name: Optional[str] = None
