from external_offers.services.clients.update_client_reason_of_decline import update_client_reason_of_decline_public
from external_offers.services.clients.update_client_additional_numbers import update_client_additional_numbers_public
from external_offers.services.clients.update_client_additional_emails import update_client_additional_emails_public