# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client users`

cian-codegen version: 1.17.0

"""
from dataclasses import dataclass


@dataclass
class AddRoleToUserRequest:
    """Запрос на добавление роли"""

    role_name: str
    """Название роли"""
    user_id: int
    """Id пользователя"""
