# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client users`

cian-codegen version: 1.17.0

"""
from dataclasses import dataclass
from typing import List

from .role_model import RoleModel


@dataclass
class GetUserRolesResponse:
    """Ответ на получение ролей пользователя"""

    roles: List[RoleModel]
    """Роли"""
