# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client users`

cian-codegen version: 1.17.0

"""
from dataclasses import dataclass


@dataclass
class RegisteredUserDto:
    """Данные зергистрированного пользователя"""

    email: str
    """Email/логин пользователя"""
    id: int
    """Идентификатор пользователя"""
    is_agent: bool
    """Является ли пользователь агентом"""
