# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client users`

cian-codegen version: 1.16.3

"""
from dataclasses import dataclass
from typing import Optional

from .registered_user_dto import RegisteredUserDto


@dataclass
class RegisterUserByPhoneResponse:
    """Данные о результате регистрации пользователя по номеру телефона"""
    has_many_accounts: bool
    """С переданным номером телефона существует несколько учетных записей"""
    is_registered: bool
    """Зарегистрировали ли пользователя"""
    user_data: Optional[RegisteredUserDto] = None
