# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client users`

cian-codegen version: 1.16.3

"""
from dataclasses import dataclass
from datetime import datetime as _datetime
from typing import Optional

from cian_enum import NoFormat, StrEnum


class ExternalUserSourceType(StrEnum):
    __value_format__ = NoFormat
    emls = 'emls'
    """Пользователи из ЕМЛС"""
    sub_agents = 'subAgents'
    """Субагенты"""
    n1 = 'n1'
    """Партнер N1"""
    mlsn = 'mlsn'
    """Mlsn"""


class State(StrEnum):
    __value_format__ = NoFormat
    active = 'active'
    """Аткивный"""
    blocked = 'blocked'
    """Заблокирован"""
    deleted = 'deleted'
    """Удалён"""


class StateChangeReason(StrEnum):
    __value_format__ = NoFormat
    apply_sanction = 'ApplySanction'
    """Блокировка из-за санкции"""
    sub_agent = 'SubAgent'
    """Блокировка мастер-агентом"""
    remove_sanction = 'RemoveSanction'
    """Снятие санкции"""
    un_blocked_by_master_agent = 'UnBlockedByMasterAgent'
    """Снятие блокировки мастер-агентом"""
    blocked_before_remove = 'blockedBeforeRemove'
    """Блокировка перед удалением"""


@dataclass
class UserModelV2:
    """Пользователь"""
    birthday: Optional[_datetime] = None
    """Дата рождения"""
    cian_user_id: Optional[int] = None
    """CianId"""
    city: Optional[str] = None
    """Город из социальной сети"""
    creation_date: Optional[_datetime] = None
    """Дата создания пользователя"""
    email: Optional[str] = None
    """Email"""
    external_user_source_type: Optional[ExternalUserSourceType] = None
    """Тип источника"""
    first_name: Optional[str] = None
    """Имя"""
    id: Optional[int] = None
    """Id"""
    ip: Optional[int] = None
    """Ip пользователя"""
    is_agent: Optional[bool] = None
    """Является ли агентом"""
    last_name: Optional[str] = None
    """Фамилия"""
    main_announcements_region_id: Optional[int] = None
    """Основной регион работы"""
    secret_code: Optional[str] = None
    """Секретный код"""
    state: Optional[State] = None
    """Состояние пользователя"""
    state_change_reason: Optional[StateChangeReason] = None
    """Статус смены состояния"""
    user_name: Optional[str] = None
    """Имя пользователя"""
