# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client users`

cian-codegen version: 1.16.3

"""
from dataclasses import dataclass
from typing import Optional


@dataclass
class V1GetUseridsByRolename:
    role_name: Optional[str] = None
