# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client users`

cian-codegen version: 1.16.5

"""
from dataclasses import dataclass
from typing import Optional


@dataclass
class V1UserHasRole:
    role_name: Optional[str] = None
    use_cache: Optional[bool] = None
    user_id: Optional[int] = None
