# pylint: skip-file
# isort:skip_file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client sms`

cian-codegen version: 1.15.0

"""
from .send_sms_request_v2 import SendSmsRequestV2
from .send_sms_response_v2 import SendSmsResponseV2
