# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client sms`

cian-codegen version: 1.15.0

"""
from dataclasses import dataclass


@dataclass
class SendSmsResponseV2:
    """Ответ на отправку sms"""

    sms_id: int
    """Идентификатор sms"""
