# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client sms`

cian-codegen version: 1.15.0

"""
from dataclasses import dataclass
from datetime import datetime as _datetime
from typing import Optional
from uuid import UUID

from cian_enum import NoFormat, StrEnum


class MessageType(StrEnum):
    __value_format__ = NoFormat
    apply_sanction = 'applySanction'
    """Применение санкции"""
    secret_code = 'secretCode'
    """Отправка секретного кода"""
    object_confirmation_request = 'objectConfirmationRequest'
    """Требование о подтверждении"""
    public_profile_moderation = 'publicProfileModeration'
    """Модерация публичного профиля"""
    remove_party_action = 'removePartyAction'
    """Лишаем пользователя траста"""
    user_warning = 'userWarning'
    """Предупреждение"""
    rejected_announcement_checked_on_offences = 'rejectedAnnouncementCheckedOnOffences'
    """Отклоненное объявление проверено на видимые нарушения"""
    hidden_offence_warning = 'hiddenOffenceWarning'
    """Уведомление о скрытом нарушении"""
    sanction_removed = 'sanctionRemoved'
    """Снятие санкции"""
    announcement_moderated = 'announcementModerated'
    """Объявление промодерировано"""
    realtor_moderator_report = 'realtorModeratorReport'
    """Отчёт о жалобах для риэлторов-модераторов"""
    zov_changed = 'zovChanged'
    """Cообщение об изменении ЗОВ"""
    akk_verification_status_changed = 'akkVerificationStatusChanged'
    """Cообщение об изменении статуса проверки АКК"""
    user_identification_status_changed = 'userIdentificationStatusChanged'
    """Cообщение об изменении статуса идентификации пользователя"""
    user_bonuses_changed = 'userBonusesChanged'
    """Cообщение об изменении количества бонусов пользователя"""
    announcement_relevance_check = 'announcementRelevanceCheck'
    """Cообщение о проверке актуальности объявления"""
    validation_code = 'validationCode'
    """Код валидации"""
    deal_rent_document_validation_error = 'dealRentDocumentValidationError'
    """Сделка в аренде - ошибка валидации документов"""
    deal_rent_need_verification = 'dealRentNeedVerification'
    """Сделка в аренде - нужна валидация"""
    deal_requests_process = 'dealRequestsProcess'
    """Сделка - разные смс (текст динамический)"""
    tenant_interested_in_offer_rent_sms_notification = 'tenantInterestedInOfferRentSmsNotification'
    """Смс заинтересованности в предложении аренды"""
    daily_tenant_interested_in_offer_rent_sms_notification = 'dailyTenantInterestedInOfferRentSmsNotification'
    """Ежедневная смс заинтересованности в предложении аренды"""
    sms_message_after_form_status_changed = 'smsMessageAfterFormStatusChanged'
    """Смс после установки статуса анкеты"""
    auction_points_burn_down = 'auctionPointsBurnDown'
    """Аукцион - В ближайшие дни на вашем аккаунте закончатся баллы на Аукцион"""
    deal_payment_by_renter_sms_notification = 'dealPaymentByRenterSmsNotification'
    """Смс об оплате комиссии сделки арендатором"""
    user_registration = 'userRegistration'
    """Регистрация пользователя"""
    billing_promotion = 'billingPromotion'
    """Бонусные акции биллинга"""
    sleeper_notification = 'sleeperNotification'
    """Нотификация для тарифа "спящий\""""
    denied_or_delete_premium_ann = 'deniedOrDeletePremiumAnn'
    """Запрещено или удалено премиум объявление"""
    denied_or_delete_top3_ann = 'deniedOrDeleteTop3Ann'
    """Запрещено или удалено top3 объявление"""
    confirmation_code = 'confirmationCode'
    """Код подтверждения"""
    scheduled_notification = 'scheduledNotification'
    """Назначенное уведомление"""
    reject_payment = 'rejectPayment'
    """Платёж аккаунта отклонён"""
    upcoming_insufficien_funds = 'upcomingInsufficienFunds'
    'Уведомление о приближении баланса пользователя к нулю.\r\nЧтобы в размещении объявлений не возникало перерывов, пожалуйста, пополните счёт'
    zero_balance_no_overdraft = 'zeroBalanceNoOverdraft'
    'Если в ходе биллинга был достигнут, либо преодолён нулевой баланс,\r\nобычным пользователям, у которых нет кредита (овердрафта), а также тех, у которых овердрафт меньше 1 дней'
    zero_balance_within_overdraft = 'zeroBalanceWithinOverdraft'
    """В ходе биллинга был преодолён нулевой баланс, пользователям у которых есть 1-дневный кредит"""
    overdraft_expired = 'overdraftExpired'
    """Истёк срок кредита у пользователей с 1-м дневным кредитом"""
    incoming_payment = 'incomingPayment'
    """Уведомление о входящем платеже"""
    add_form_poll_invitation = 'addFormPollInvitation'
    """Приглашение к опросу по форме подачи"""
    mobile_registration_sms = 'mobileRegistrationSms'
    """Смс с логином и паролем после авторегистрации"""
    package_activated = 'packageActivated'
    """Тариф пользователя активирован"""
    deal_apply_sms_notification = 'dealApplySmsNotification'
    """Смс об успешной оплате сделки в аренде"""
    homeowner_deleted_offer_with_unprocessed_forms = 'homeownerDeletedOfferWithUnprocessedForms'
    """Смс о том, что собственник удалил объявление с непросмотренными анкетами"""
    homeowner_deactivated_offer_with_unprocessed_forms = 'homeownerDeactivatedOfferWithUnprocessedForms'
    """Смс о том, что собственник снял объявление с публикации с непросмотренными анкетами"""
    scoring_completed_to_renter_sms_notification = 'scoringCompletedToRenterSmsNotification'
    """Смс об заврешении скоринга"""
    form_published_sms_notification = 'formPublishedSmsNotification'
    """Смс о публикации анкеты сделки в аренде"""
    finance_authentication_code = 'financeAuthenticationCode'
    """Финансы: коды авторизации"""
    finance_marketing_communication = 'financeMarketingCommunication'
    """Финансы: коммунакация"""
    finance_mortgage_approve = 'financeMortgageApprove'
    """Финансы: Ипотека одобрена"""
    finance_after_application_sent = 'financeAfterApplicationSent'
    """Финансы: заявка принята"""
    finance_cabinet_created = 'financeCabinetCreated'
    """Финансы: ЛК создан"""
    finance_default = 'financeDefault'
    """Финансы: другое"""
    keycloak = 'keycloak'
    """Двухфакторная аунтентификация для Keycloak"""
    denied_or_deleted_top3_or_premium = 'deniedOrDeletedTop3OrPremium'
    """TOP-3 или Премиум объявление удалено/отклонено"""
    contract_to_renter_sms_notification = 'contractToRenterSmsNotification'
    """Смс со ссылкой на контракт для арендатора"""
    payment_status_to_homeowner_sms_notification = 'paymentStatusToHomeownerSmsNotification'
    """СМС уведомление собу о статусе платежа"""
    cancel_contract_to_homeowner_sms_notification = 'cancelContractToHomeownerSmsNotification'
    """СМС уведомление собу об отмене контракта"""
    sdaysnimi_homeowner_should_set_meters = 'sdaysnimiHomeownerShouldSetMeters'
    """СМС уведомление собственнику "Укажите сумму по счетчикам\""""
    sdaysnimi_rent_paid = 'sdaysnimiRentPaid'
    """СМС уведомление собственнику \\"Арендатор оплатил аренду за этот месяц\\\""""
    sdaysnimi_rent_payment_with_meters = 'sdaysnimiRentPaymentWithMeters'
    """СМС уведомление \\"Cобственник уже внес данные по счетчикам\\\""""
    sdaysnimi_rent_payment_without_meters = 'sdaysnimiRentPaymentWithoutMeters'
    """СМС уведомление \\"Собственник еще не внес данные по счетчикам\\\""""
    sdaysnimi_rent_payment_last_day = 'sdaysnimiRentPaymentLastDay'
    """СМС уведомление \\"Оплата ещё не была произведена\\\""""
    sdaysnimi_rent_receipt_link = 'sdaysnimiRentReceiptLink'
    """СМС уведомление со ссылкой на чек после оплаты аренды"""
    sdaysnimi_renter_is_waiting_decision = 'sdaysnimiRenterIsWaitingDecision'
    """СМС уведомление "Арендатор всё ещё ждёт вашего решения\""""
    sdaysnimi_renters_are_waiting_decision = 'sdaysnimiRentersAreWaitingDecision'
    """СМС уведомление "У вас N потенциальных арендаторов\""""
    sdaysnimi_renter_still_did_not_get_decision = 'sdaysnimiRenterStillDidNotGetDecision'
    """СМС уведомление "Арендатор так и не получил решения по анкете\""""
    sdaysnimi_renters_still_did_not_get_decision = 'sdaysnimiRentersStillDidNotGetDecision'
    """СМС уведомление "Арендаторы ждут вашего решения больше 24 часов\""""
    spam_phone_number_blocked_for_day = 'spamPhoneNumberBlockedForDay'
    """СМС уведомление "Номер телефона заблокирован за спам на 1 сутки\""""
    sdaysnimi_more_renters_are_interested_in_offer = 'sdaysnimiMoreRentersAreInterestedInOffer'
    """СМС-уведомление "Вашей квартирой заинтересовались ещё N арендаторов\""""
    sdaysnimi_deal_activated = 'sdaysnimiDealActivated'
    """СМС-уведомление "Мы подключили к вашему объявлению сервис “Сдай / Сними“: https://promo.cian.ru/sday-snimi-how-to. Для собственников квартир он бесплатен\""""
    sdaysnimi_identification_farewell = 'sdaysnimiIdentificationFarewell'
    'Услуга Сдай / Сними отключена, т.к. вы не прошли идентификацию.\r\nПосле ее прохождения можете снова оставить заявку на услугу.\r\nБудут вопросы, звоните +7-499-288-80-23'
    sdaysnimi_identification_warning = 'sdaysnimiIdentificationWarning'
    'Пройдите идентификацию, чтобы мы могли опубликовать ваше объявление. \r\nЗайдите в личном кабинете во вкладку «Профиль», нажмите «Пройти проверку» и загрузите документы. \r\nБудут вопросы, звоните +7-499-288-80-23'
    sdaysnimi_offer_and_identification_farewell = 'sdaysnimiOfferAndIdentificationFarewell'
    'Услуга Сдай / Сними отключена, т.к. вы не прошли идентификацию и не разместили объявление. \r\nМожете снова оставить заявку на услугу. \r\nБудут вопросы, звоните +7-499-288-80-23'
    sdaysnimi_offer_and_identification_warning = 'sdaysnimiOfferAndIdentificationWarning'
    'Услуга Сдай / Сними подключена. \r\nЧтобы ее активировать, разместите объявление на Циан и пройдите идентификацию в разделе «Профиль» в личном кабинете. \r\nБудут вопросы, звоните +7-499-288-80-23'
    sdaysnimi_offer_farewell = 'sdaysnimiOfferFarewell'
    'Услуга Сдай / Сними отключена, т.к. вы не разместили объявление. \r\nМожете снова оставить заявку на услугу. \r\nБудут вопросы, звоните +7-499-288-80-23'
    sdaysnimi_offer_warning = 'sdaysnimiOfferWarning'
    'Услуга Сдай / Сними подключена. \r\nЧтобы ее активировать, разместите объявление на Циан. \r\nБудут вопросы, звоните +7-499-288-80-23'
    sdaysnimi_renter_accept_contract = 'sdaysnimiRenterAcceptContract'
    'СМС-уведомление\r\nПоздравляем! %Имя арендатора% подписал(а) договор аренды.\r\nВ ближайшее время ожидайте оплату аренды по договору, мы вышлем вам смс'
    renter_scoring_error = 'renterScoringError'
    'СМС-уведомление\r\nК сожалению, при проверке документов произошла ошибка. Повторно загрузить документы %ссылка%'
    renter_scoring_success = 'renterScoringSuccess'
    'СМС-уведомление\r\nДокументы проверены! Теперь вы можете ознакомиться с договором аренды и подписать его онлайн %ссылка%'
    sdaysnimi_scheduled_show_date = 'sdaysnimiScheduledShowDate'
    'СМС-уведомление\r\nВы записаны на показ квартиры в (дата время). Адрес квартиры: (адрес). Телефон собственника для связи: (телефон)'
    sdaysnimi_show_date_remember = 'sdaysnimiShowDateRemember'
    'СМС-уведомление\r\nВы записаны на показ квартиры (дата время). Если вы не сможете приехать, пожалуйста, позвоните нам +7-499-288-80-23 и отмените показ'
    sdaysnimi_show_date_homeowner_remember = 'sdaysnimiShowDateHomeownerRemember'
    'СМС-уведомление\r\nНовая запись на просмотр квартиры %дата время%. Телефон арендатора %номер%'
    sdaysnimi_renter_contract_payment_reminder = 'sdaysnimiRenterContractPaymentReminder'
    'СМС-уведомление\r\nУспейте оплатить аренду по договору до %чч% %дд%, иначе договор аренды будет автоматически расторгнут'
    sdaysnimi_homeowner_contract_payment_reminder = 'sdaysnimiHomeownerContractPaymentReminder'
    'СМС-уведомление\r\n%Имя арендатора% пока не оплатил аренду. Если оплата не будет проведена до %чч% %дд%, договор будет автоматически расторгнут.'
    sdaysnimi_renter_contract_payment_expire = 'sdaysnimiRenterContractPaymentExpire'
    'СМС-уведомление\r\nВы не провели оплату за аренду по договору. Договор аренды расторгнут. Вы можете запросить повторное подписание договора связавшись напрямую с собственником.'
    sdaysnimi_homeowner_contract_payment_expire = 'sdaysnimiHomeownerContractPaymentExpire'
    'СМС-уведомление\r\n%Имя арендатора% не произвел оплату по договору. Договор аренды расторгнут. Вы можете выбрать другого арендатора %ссылка на страницу с выбором арендатора%'
    sdaysnimi_unprocessed_forms_warning = 'sdaysnimiUnprocessedFormsWarning'
    """СМС-уведомление "Здравствуйте! У вас есть непросмотренные анкеты арендаторов\""""
    sdaysnimi_offer_relevance_confirmation = 'sdaysnimiOfferRelevanceConfirmation'
    """СМС-уведомление "Здравствуйте! Пожалуйста, подтвердите актуальность вашего объявления на Циан по ссылке\""""
    sdaysnimi_deal_was_automatically_deactivated = 'sdaysnimiDealWasAutomaticallyDeactivated'
    """СМС-уведомление "Услуга Сдай / Сними отключена. Если вы хотите заново подключить услугу, вы можете сделать это в личном кабинете\""""
    sdaysnimi_liquid_offer_invite_v1 = 'sdaysnimiLiquidOfferInviteV1'
    'СМС-уведомление "Слишком много звонков? Циан может принимать звонки за вас и отправлять вам анкеты арендаторов.\r\nЭто бесплатно https://www.cian.ru/arenda-oplata/"'
    sdaysnimi_liquid_offer_invite_v2 = 'sdaysnimiLiquidOfferInviteV2'
    'СМС-уведомление "Слишком много звонков? Циан может принимать звонки за вас и отправлять вам анкеты арендаторов.\r\nЭто бесплатно http://promo.cian.ru/arenda-bez-riska-apps"'
    sdaysnimi_auto_search_for_renter_deactivated = 'sdaysnimiAutoSearchForRenterDeactivated'
    """СМС-уведомление "Действие услуги «Автоматический подбор квартир» закончилось\""""
    sdaysnimi_similar_offers_after_declined_form = 'sdaysnimiSimilarOffersAfterDeclinedForm'
    """СМС-уведомление "Отправить вашу анкету на похожие квартиры?\""""
    sdaysnimi_offer_was_automatically_archived = 'sdaysnimiOfferWasAutomaticallyArchived'
    """СМС-уведомление "Ваше объявление было автоматически снято с показа. Если его требуется восстановить, обратитесь в службу поддержки по телефону +7-499-288-80-23\""""
    sdaysnimi_homeowner_show_date_scheduled_sms_notification = 'sdaysnimiHomeownerShowDateScheduledSmsNotification'
    """СМС-уведомление "Сегодня в %чч:мм% у вас назначен показ квартиры. Если вы хотите отменить показ, пожалуйста, предупредите арендатора %номер телефона арендатора%\""""
    mobile_app_link = 'mobileAppLink'
    """Ссылка на мобильное приложение"""
    sday_snimi_deal_subscription_payment = 'sdaySnimiDealSubscriptionPayment'
    """СМС-уведомление "Завтра заканчивается действие услуги «Сдай/Сними», для продолжения оплатите следующие 7 дней %ссылка на оплату%\""""
    sdaysnimi_first_view_offer_invite = 'sdaysnimiFirstViewOfferInvite'
    """СМС-уведомление "Если вас беспокоят навязчивые звонки, мы можем принимать их за вас. Это бесплатно %ссылка на промо%\""""
    sdaysnimi_deal_subscription_payment_required = 'sdaysnimiDealSubscriptionPaymentRequired'
    """СМС-уведомление "Мы получили вашу заявку на подключение, чтобы активировать сервис вам необходимо оплатить 299₽ за неделю размещения %ссылка на оплату%\""""
    sdaysnimi_deal_subscription_warning = 'sdaysnimiDealSubscriptionWarning'
    """СМС-уведомление "Ваше объявление неактивно на сайте. Для его активации вам нужно оплатить 7 дней размещения %ссылка на оплату%\""""
    sdaysnimi_deal_subscription_farewell = 'sdaysnimiDealSubscriptionFarewell'
    """СМС-уведомление "Ваше объявление отключено от Сдай/Сними, т.к. вы не оплатили размещение. Вы можете подключиться заново из вашего личного кабинета\""""
    sdaysnimi_homeowner_tax_reminder = 'sdaysnimiHomeownerTaxReminder'
    """СМС-уведомление "Напоминаем, что с 12.%ММ% по 25.%ММ% вам необходимо проверить сумму начисленных налогов и оплатить их в личном кабинете https://lknpd.nalog.ru/ или приложении Мой налог\""""
    sdaysnimi_homeowner_published_for_free_with_unprocessed_forms = (
        'sdaysnimiHomeownerPublishedForFreeWithUnprocessedForms'
    )
    """СМС-уведомление "Теперь вы можете связаться с собственником квартиры %ссылка на объявление% по номеру телефона в объявлении\""""
    sdaysnimi_sanctioned_deal_forms = 'sdaysnimiSanctionedDealForms'
    """Мы обнаружили, что объявление, на которое вы откликались, недостоверно. Не переводите деньги и будьте осторожны. %адрес объявления, без города% %ссылка на объявление%"""
    sdaysnimi_forms_count_limit_exceeded_for_trial = 'sdaysnimiFormsCountLimitExceededForTrial'
    """Ваше объявление получило %кол-во анкет% анкет от арендаторов. Для просмотра остальных анкет, оплатите следующие 7 дней %ссылка на оплату%"""
    sdaysnimi_force_homeowner_flow = 'sdaysnimiForceHomeownerFlow'
    """Вы подключили сервис Сдай/Сними от Циан. Теперь загрузите недостающие паспортные данные, чтобы мы могли составить договор аренды. %ссылка на ЛК%"""
    sdaysnimi_identification_and_offences_warning = 'sdaysnimiIdentificationAndOffencesWarning'
    """Чтобы опубликовать объявление и подключиться к сервису Сдай/Сними, пожалуйста, пройдите идентификацию и исправьте нарушения"""
    sdaysnimi_identification_and_offences_farewell = 'sdaysnimiIdentificationAndOffencesFarewell'
    'Мы не смогли подключить услугу Сдай/Сними, т.к. вы не прошли идентификацию и не исправили нарушения. Ваше объявление не опубликовано.\r\nПожалуйста, пройдите идентификацию и исправьте нарушения. После этого снова подключитесь к сервису Сдай/Сними'
    sdaysnimi_offences_warning = 'sdaysnimiOffencesWarning'
    """В вашем объявлении выявлены нарушения, пожалуйста, зайдите в личный кабинет и исправьте их, чтобы объявление опубликовалось"""
    sdaysnimi_offences_farewell = 'sdaysnimiOffencesFarewell'
    'Мы не смогли подключить услугу Сдай/Сними, т.к. в объявлении не были исправлены нарушения. Ваше объявление не опубликовано.\r\nПожалуйста, исправьте нарушения и снова подключитесь к сервису Сдай/сними'
    sdaysnimi_price_limit_exceeded = 'sdaysnimiPriceLimitExceeded'
    """К сожалению, нам не удастся подключить сервис Сдай/Сними для вас. Сервис предназначен для квартир дешевле %лимит% ₽"""
    sdaysnimi_deal_v2_service_activation_warning = 'sdaysnimiDealV2ServiceActivationWarning'
    """Ваше объявление всё еще не активно на сайте. Для активации объявления оплатите 990₽ в вашем личном кабинете http://my.cian.ru/"""
    sdaysnimi_deal_v2_service_activation_farewell = 'SdaysnimiDealV2ServiceActivationFarewell'
    'Сервис Сдай/Сними отключен, так как вы не произвели оплату. Ваше объявление не опубликовано.\r\nДля публикации объявления перейдите в личный кабинет http://my.cian.ru/'
    sdaysnimi_deal_v2_service_activation_payment_warning = 'sdaysnimiDealV2ServiceActivationPaymentWarning'
    """Ваше объявление не активно на сайте. Для активации объявления с сервисом Сдай/Сними оплатите 990₽ по ссылке %ссылка на оплату%"""
    sdaysnimi_bank_is_not_bound = 'sdaysnimiBankIsNotBound'
    """Для получения арендных платежей необходимо ваше разрешение. Подробности в личном кабинете %ссылка на ЛК%"""
    sdaysnimi_offer_report = 'sdaysnimiOfferReport'
    """Подготовили для вас аналитический отчет по вашей квартире. Посмотрите его по ссылке %ссылка на калькулятор недвижимости%"""
    sdaysnimi_inn_required = 'sdaysnimiInnRequired'
    """Нужен ваш ИНН, укажите его в личном кабинете"""
    sdaysnimi_candidate_in_blacklist = 'sdaysnimiCandidateInBlacklist'
    """Сервис Сдай/Сними был отключён от вашего объявления. Теперь оно опубликовано на общих условиях"""
    sdaysnimi_renter_paid_the_rent_for_homeowner = 'sdaysnimiRenterPaidTheRentForHomeowner'
    """Перевели оплату аренды, деньги могут идти пару дней - зависит от банка"""
    sdaysnimi_homeowner_checks_required_after_renter_payment = 'sdaysnimiHomeownerChecksRequiredAfterRenterPayment'
    """Вам перевели оплату; получите ее - настройте профиль в течение 5 дней"""
    sdaysnimi_renter_identification_required_after_payment = 'sdaysnimiRenterIdentificationRequiredAfterPayment'
    """Получили оплату от арендатора; проверяем паспорт"""
    sdaysnimi_wait_renter_contract_sign_after_identification = 'sdaysnimiWaitRenterContractSignAfterIdentification'
    """С паспортом арендатора всё хорошо; ждём подписания договора"""
    sdaysnimi_renter_cancel_contract = 'sdaysnimiRenterCancelContract'
    """Арендатор передумал, и нам пришлось вернуть ему деньги; выберите другого"""
    sdaysnimi_renter_not_sign_contract_for_homeowner = 'sdaysnimiRenterNotSignContractForHomeowner'
    """Арендатор так и не подписал договор - вернули ему деньги"""
    sdaysnimi_renter_payment_refund_for_homeowner = 'sdaysnimiRenterPaymentRefundForHomeowner'
    """Пришлось вернуть деньги арендатору: вы не настроили свой профиль"""
    sdaysnimi_identification_required_after_renter_payment = 'sdaysnimiIdentificationRequiredAfterRenterPayment'
    """Получили оплату; давайте подпишем договор - добавьте паспорт в профиль"""
    sdaysnimi_identification_error_after_renter_payment = 'sdaysnimiIdentificationErrorAfterRenterPayment'
    """С паспортом что-то не так, попробуйте добавить его ещё раз. Если не получается, звоните на %телефон колцентра%"""
    sdaysnimi_identification_success_wait_for_homeowner_checks = 'sdaysnimiIdentificationSuccessWaitForHomeownerChecks'
    """С паспортом всё хорошо; ждём, пока собственник настроит свой профиль"""
    sdaysnimi_contract_ready_for_signing = 'sdaysnimiContractReadyForSigning'
    """Договор готов! Подпишите его  %link%"""
    sdaysnimi_homeowner_cancel_contract = 'sdaysnimiHomeownerCancelContract'
    """Собственник передумал :( вернули вам деньги - проверьте, пожалуйста"""
    sdaysnimi_renter_payment_refund_cause_homeowner = 'sdaysnimiRenterPaymentRefundCauseHomeowner'
    """Собственник не настроил профиль, сделка отменена; вернули вам деньги"""
    sdaysnimi_renter_payment_refund = 'sdaysnimiRenterPaymentRefund'
    """Отменили сделку и вернули вам деньги: вы не успели подписать договор"""
    b2b_smb_welcome_instruction = 'b2bSmbWelcomeInstruction'
    """Инструкция для агента. Ваше объявление ожидает публикации на Циан"""
    b2b_homeowner_welcome_instruction = 'b2bHomeownerWelcomeInstruction'
    """Инструкция для собственника. Ваше объявление ожидает публикации на Циан"""
    e2_e_deal_payment_link = 'e2EDealPaymentLink'
    """Ваш риелтор заполнил анкету на проведение электронной сделки и просит вас оплатить услуг %link%"""


@dataclass
class SendSmsRequestV2:
    """Запрос на отправку sms."""

    message_type: MessageType
    """Тип отправляемого смс-сообщения"""
    phone: str
    'Номер телефона.\r\nНапример, "79101234567"'
    text: str
    'Текст sms-сообщения.\r\nНе более 250 символов.'
    deferred_send_date: Optional[_datetime] = None
    """Дата отложенной отправки"""
    transaction_id: Optional[UUID] = None
    'Идентификатор транзакции\r\nПредотвращает повторную отправку sms'
