# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client announcements`

cian-codegen version: 1.17.0

"""
from ._repo import public_v1_get_possible_appointments, v2_get_user_active_announcements_count
