# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client announcements`

cian-codegen version: 1.7.1

"""
from cian_http.api_client import Api

from . import entities


_api = Api(microservice_name='announcements')
v2_get_user_active_announcements_count = _api.make_client(
    path='/v2/get-user-active-announcements-count/',
    method='GET',
    handle_http_exceptions=True,
    request_schema=entities.V2GetUserActiveAnnouncementsCount,
    response_schema=entities.GetAnnouncementCountResponse,
)
