# pylint: skip-file
# isort:skip_file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client announcements`

cian-codegen version: 1.7.1

"""
from .get_announcement_count_response import GetAnnouncementCountResponse
from .v2_get_user_active_announcements_count import V2GetUserActiveAnnouncementsCount
