# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client announcements`

cian-codegen version: 1.17.0

"""
from dataclasses import dataclass


@dataclass
class GetPossibleAppointmentItem:
    """Элемент "Возможное назначение" готового бизнеса."""

    id: int
    """Id."""
    name: str
    """Название."""
