# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client announcements`

cian-codegen version: 1.17.0

"""
from dataclasses import dataclass
from typing import List

from .get_possible_appointment_item import GetPossibleAppointmentItem


@dataclass
class GetPossibleAppointmentsResponse:
    """Ответ на запрос получения справочника "Возможное назначение" готового бизнеса."""

    items: List[GetPossibleAppointmentItem]
    """Список элементов с возможным назначением готового бизнеса."""
