# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-announcementapi`

cian-codegen version: 1.17.0

"""
from dataclasses import dataclass
from datetime import datetime as _datetime
from typing import Optional
from uuid import UUID

from .swagger_object_model import SwaggerObjectModel


@dataclass
class AnnouncementReportingChangedQueueMessage:
    date: _datetime
    model: Optional[SwaggerObjectModel] = None
    """Модель объявления"""
    operation_id: Optional[UUID] = None
