# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-announcementapi`

cian-codegen version: 1.17.0

"""
from dataclasses import dataclass
from typing import Optional


@dataclass
class CommercialPossibleAppointmentModel:
    eng_name: Optional[str] = None
    """Английское название."""
    id: Optional[int] = None
    """Id."""
    rus_name: Optional[str] = None
    """Русское название."""
