# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-announcementapi`

cian-codegen version: 1.17.0

"""
from dataclasses import dataclass
from typing import List, Optional

from cian_enum import NoFormat, StrEnum

from .details import Details
from .geo import Geo


class AccuracyError(StrEnum):
    __value_format__ = NoFormat
    street_required = 'streetRequired'
    """Требуется улица"""
    house_required = 'houseRequired'
    """Требуется дом"""


@dataclass
class GeoCodeAnnouncementResponse:
    accuracy_error: Optional[AccuracyError] = None
    """Ошибка неточности адреса"""
    billing_region_id: Optional[int] = None
    """Идентификатор региона тарифной сетки."""
    country_id: Optional[int] = None
    """ID страны"""
    details: Optional[List[Details]] = None
    """Содержит в себе массив объектов, каждый из которых описывает часть адреса (то что разделено запятыми)."""
    geo: Optional[Geo] = None
    """Информация по Гео (широта, долгота)."""
    is_parsed: Optional[bool] = None
    """Если удалось распарсить адрес."""
    location_path: Optional[List[int]] = None
    'Идентификаторы всех локаций, от родительского до самого точного\r\nИспользуется в биллинге'
    text: Optional[str] = None
    """Результат яндекса после геокодинга."""
