# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-announcementapi`

cian-codegen version: 1.17.0

"""
from dataclasses import dataclass
from datetime import datetime as _datetime
from typing import List, Optional

from cian_enum import NoFormat, StrEnum

from .publish_term import PublishTerm


class MainService(StrEnum):
    __value_format__ = NoFormat
    free = 'free'
    """Бесплатное"""
    highlight = 'highlight'
    """<a href="http://www.cian.ru/promo/adv/#color" target="_blank">Выделение цветом</a>"""
    paid = 'paid'
    """Платное"""
    premium = 'premium'
    """<a href="http://www.cian.ru/promo/adv/#premium" target="_blank">Премиум-объявление</a>"""
    top3 = 'top3'
    """<a href="http://www.cian.ru/promo/adv/#top3" target="_blank">Топ</a>"""
    calltracking = 'calltracking'
    """Защита номера"""
    auction = 'auction'
    """Аукцион"""


class SelectedService(StrEnum):
    __value_format__ = NoFormat
    free = 'free'
    """Бесплатное"""
    highlight = 'highlight'
    """<a href="http://www.cian.ru/promo/adv/#color" target="_blank">Выделение цветом</a>"""
    paid = 'paid'
    """Платное"""
    premium = 'premium'
    """<a href="http://www.cian.ru/promo/adv/#premium" target="_blank">Премиум-объявление</a>"""
    top3 = 'top3'
    """<a href="http://www.cian.ru/promo/adv/#top3" target="_blank">Топ</a>"""
    calltracking = 'calltracking'
    """Защита номера"""
    auction = 'auction'
    """Аукцион"""


@dataclass
class PublishTerms:
    'Условия размещения объявления\r\nСрок размещения платного в аренде жилой 7 дней, продаже жилой 30 дней.\r\nСрок размещения платного в аренде коммерческой 30 дней, продаже коммерческой 30 дней.\r\nПремиум и Топ размещение - посуточно.\r\nСрок действия Выделенние цветом такой же, как и у размещения на которое вы его добавляете (платное или премиум)'
    actor_user_id: Optional[int] = None
    """Id пользователя инициировавшего размещение"""
    autoprolong: Optional[bool] = None
    """Автопродление включено"""
    expiration_date: Optional[_datetime] = None
    """Дата окончания публикации"""
    infinite_publish_period: Optional[bool] = None
    'Если true, то будет использован бесконечный период публикации.\r\nТолько для выгрузок, при ручной подаче игнорируем.'
    main_service: Optional[MainService] = None
    """Основная услуга, используется для выдачи"""
    payer_user_id: Optional[int] = None
    """Id пользователя оплативнего размещение"""
    publication_term: Optional[PublishTerm] = None
    """Условия публикации, используется для основного контракта"""
    selected_service: Optional[SelectedService] = None
    """Выбранная услуга, используется для стратегий"""
    skip_billing: Optional[bool] = None
    'Пропускает биллинг объявления.\r\nТолько для выгрузок, при ручной подаче игнорируем.'
    skip_minimal_price_check: Optional[bool] = None
    'Пропустить проверку минимальной цены.\r\nТолько для выгрузок, при ручной подаче игнорируем.'
    terms: Optional[List[PublishTerm]] = None
    """Условия размещения"""
    use_promotion_from_auction: Optional[bool] = None
    """Использовать стоимость аукциона как итоговую стоимость продвижения"""
