# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-announcementapi`

cian-codegen version: 1.17.0

"""
from dataclasses import dataclass
from typing import Optional

from .self_employed import SelfEmployed


@dataclass
class UserData:
    """Данные о пользователе, передаваемые при публикации объявления"""

    self_employed_data: Optional[SelfEmployed] = None
    """Данные о статусе самозанятости пользователя"""
