# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-announcementapi`

cian-codegen version: 1.9.0

"""
from dataclasses import dataclass
from typing import Optional

from cian_enum import NoFormat, StrEnum


class Category(StrEnum):
    __value_format__ = NoFormat
    bed_rent = 'bedRent'
    """Койко-место"""
    building_rent = 'buildingRent'
    """Здание"""
    building_sale = 'buildingSale'
    """Здание"""
    business_rent = 'businessRent'
    """Готовый бизнес"""
    business_sale = 'businessSale'
    """Готовый бизнес"""
    car_service_rent = 'carServiceRent'
    """Аренда автосервис"""
    car_service_sale = 'carServiceSale'
    """Продажа автосервиса"""
    commercial_land_rent = 'commercialLandRent'
    """Коммерческая земля"""
    commercial_land_sale = 'commercialLandSale'
    """Коммерческая земля"""
    cottage_rent = 'cottageRent'
    """Коттедж"""
    cottage_sale = 'cottageSale'
    """Коттедж"""
    daily_bed_rent = 'dailyBedRent'
    """Посуточная аренда койко-места"""
    daily_flat_rent = 'dailyFlatRent'
    """Посуточная аренда квартиры"""
    daily_house_rent = 'dailyHouseRent'
    """Посуточная аренда дома, дачи, коттеджа"""
    daily_room_rent = 'dailyRoomRent'
    """Посуточная аренда комнаты"""
    domestic_services_rent = 'domesticServicesRent'
    """Аренда помещения под бытовые услуги"""
    domestic_services_sale = 'domesticServicesSale'
    """Продажа помещения под бытовые услуги"""
    flat_rent = 'flatRent'
    """Квартира"""
    flat_sale = 'flatSale'
    """Квартира"""
    flat_share_sale = 'flatShareSale'
    """Доля в квартире"""
    free_appointment_object_rent = 'freeAppointmentObjectRent'
    """Помещение свободного назначения"""
    free_appointment_object_sale = 'freeAppointmentObjectSale'
    """Помещение свободного назначения"""
    garage_rent = 'garageRent'
    """Гараж"""
    garage_sale = 'garageSale'
    """Гараж"""
    house_rent = 'houseRent'
    """Дом/дача"""
    house_sale = 'houseSale'
    """Дом/дача"""
    house_share_rent = 'houseShareRent'
    """Часть дома"""
    house_share_sale = 'houseShareSale'
    """Часть дома"""
    industry_rent = 'industryRent'
    """Производство"""
    industry_sale = 'industrySale'
    """Производство"""
    land_sale = 'landSale'
    """Участок"""
    new_building_flat_sale = 'newBuildingFlatSale'
    """Квартира в новостройке"""
    office_rent = 'officeRent'
    """Офис"""
    office_sale = 'officeSale'
    """Офис"""
    public_catering_rent = 'publicCateringRent'
    """Аренда общепита"""
    public_catering_sale = 'publicCateringSale'
    """Продажа общепита"""
    room_rent = 'roomRent'
    """Комната"""
    room_sale = 'roomSale'
    """Комната"""
    shopping_area_rent = 'shoppingAreaRent'
    """Торговая площадь"""
    shopping_area_sale = 'shoppingAreaSale'
    """Торговая площадь"""
    townhouse_rent = 'townhouseRent'
    """Таунхаус"""
    townhouse_sale = 'townhouseSale'
    """Таунхаус"""
    warehouse_rent = 'warehouseRent'
    """Склад"""
    warehouse_sale = 'warehouseSale'
    """Склад"""


class Source(StrEnum):
    __value_format__ = NoFormat
    unknown = 'Unknown'
    """Не определено, проставляется по умолчанию, если source = null"""
    machine_learning = 'MachineLearning'
    """Запрос от ML, нужно выяснить в каких случаях они запрашивают GeocodeApi"""
    address_search_filter_service = 'AddressSearchFilterService'
    'Используется только в AddressSearchFilterService, а тот в свою очередь\r\nпохоже, что нигде не используется. \r\nКандидат на выпиливание.'
    check_yandex_definite_address = 'CheckYandexDefiniteAddress'
    """Используется при добивании адреса данными из наших справочников"""
    try_insert = 'TryInsert'
    """Указывается при попытке добавить в нашу БД улицы, локации, дома"""
    api_geo_search_address = 'ApiGeoSearchAddress'
    'Возможно нигде не используется, в монолите нет на него ссылок,\r\nтак же в графане нет такой метрики. \r\nКандидат на выпиливание.'
    import_ = 'Import'
    """Используется при импорте IUploadImportService"""
    import_get_geo_coded_result_by_query = 'ImportGetGeoCodedResultByQuery'
    """Используется при импорте для поиска наиболее подходящего адреса"""
    map_address = 'MapAddress'
    'Используется для маппинга адреса на справочники в нашей системе на сайте cian\r\napi/geo/map-address/\r\nТакже используется при импорте фидов CianNewFeed'
    import_ebd_transformation_entry = 'ImportEbdTransformationEntry'
    'Не найдено ссылок в монолите, так же не видно такой метрики в графане,\r\nвозможно дергается редко сторонними сервисами.\r\nКандидат на выпиливание'
    import_get_yandex_geo_route = 'ImportGetYandexGeoRoute'
    'Используется для получения GeoRoute при импорте \r\nAvito / Cian / NewObjects'
    import_yrl_transformation_entry = 'ImportYrlTransformationEntry'
    """Используется при импорте фидов YandexRealty, при трансформации гео-данных"""
    bi_emls_fill_orders = 'BiEmlsFillOrders'
    """Используется таском по заполнению Emls OrderFacts (факт оплаты), при получении локации"""
    moderation = 'Moderation'
    """Используется при привязке адреса к нашим справочникам гео-модератором"""
    process_geo_check_item_command = 'ProcessGeoCheckItemCommand'
    """Используется сервисом по обработке гео-элементов на проверку"""
    rebinding = 'Rebinding'
    """Используется сервисом по перепривязке объявлений"""
    try_add_addresses_at_rebind = 'TryAddAddressesAtRebind'
    'Используется сервисом по перепривязке гео у объектов при попытке добавить адрес\r\nIRebindByGeoService'
    settler = 'Settler'
    'Не найдено ссылок в монолите, так же не видно такой метрики в графане,\r\nвозможно дергается редко сторонними сервисами.\r\nКандидат на выпиливание'
    try_add_addresses_at_emls_jk_import = 'TryAddAddressesAtEmlsJkImport'
    """Выгрузка EMLS из xml при попытке добавить адрес"""
    emls_jk_import = 'EmlsJkImport'
    """Выгрузка EMLS из xml"""
    geo_code_cached = 'GeoCodeCached'
    'Используется в методе для заглушки JS метода ymaps.geocode\r\nЧтобы не грузить Яндекс большим количеством запросов, кешируем их у себя\r\napi/geo/geocode-cached/'
    site = 'Site'
    'Указывается при поиске по адресу на сайте cian\r\napi/geo/geocoded/ и api/geo/get-address/'
    unload_page = 'UnloadPage'
    'Не найдено ссылок в монолите, так же не видно такой метрики в графане,\r\nвозможно дергается редко сторонними сервисами.\r\nКандидат на выпиливание'
    geo_api_geocode = 'GeoApiGeocode'
    'Использовалось для всех анонимных источников, теперь\r\nдля этого будет служить Unknown'
    site_admin = 'SiteAdmin'
    'Используется service.cian при получении нашего адреса, который может быть перепривязан\r\nIGeoAutocompleteService метод GeoCode'
    refresh_cache = 'RefreshCache'
    """Указывается при обновлении кеша Яндекса гео-модератором"""
    mobile_api = 'MobileApi'
    'Используется мобильным Api при геокодирование расположения объекта\r\nhttps://cianru.atlassian.net/wiki/pages/viewpage.action?pageId=17399972\r\nv1/geo/geocode_location/'
    rebind = 'Rebind'
    'Используется сервисом по перепривязке гео у объектов\r\nIRebindByGeoService'
    sandbox = 'Sandbox'
    """Указывается при вызове из Sandbox"""
    announcement_parser = 'AnnouncementParser'
    'Не найдено ссылок в монолите, так же не видно такой метрики в графане,\r\nвозможно дергается редко сторонними сервисами.\r\nКандидат на выпиливание'
    add_form = 'AddForm'
    """Форма подачи"""
    valuation = 'Valuation'
    """Оценка недвижимости"""


@dataclass
class V1GeoGeocode:
    category: Category
    """Категория"""
    request: str
    """Текс запроса"""
    source: Optional[Source] = None
    """Источник"""
