# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client moderation-confidence-index`

cian-codegen version: 1.17.0

"""
from ._repo import api_call_component_v1_get_operator_calls
