# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client moderation-confidence-index`

cian-codegen version: 2.0.0

"""
from cian_http.api_client import Api

from . import entities


_api = Api(microservice_name='moderation-confidence-index')
api_call_component_v1_get_operator_calls = _api.make_client(
    path='/api/call-component/v1/get-operator-calls',
    method='POST',
    handle_http_exceptions=True,
    request_schema=entities.GetOperatorCallsFilter,
    response_schema=entities.GetOperatorCallsResponseModel,
)
api_call_component_v1_operator_calls_create_csv_report = _api.make_client(
    path='/api/call-component/v1/operator-calls/create-csv-report',
    method='POST',
    handle_http_exceptions=True,
    request_schema=entities.GetOperatorCallsFilter,
    response_schema=entities.GenerateCsvResponseModel,
)
api_call_component_v1_operator_calls_download_csv_reportcsv = _api.make_client(
    path='/api/call-component/v1/operator-calls/download-csv-report.csv',
    method='GET',
    handle_http_exceptions=True,
    request_schema=entities.ApiCallComponentV1OperatorCallsDownloadCsvReportcsv,
)
api_call_component_v1_operator_calls_get_csv_report_status = _api.make_client(
    path='/api/call-component/v1/operator-calls/get-csv-report-status',
    method='POST',
    handle_http_exceptions=True,
    request_schema=entities.GetCsvReportStatusRequestModel,
    response_schema=entities.GetCsvReportStatusResponseModel,
)
