# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-profileapi`

cian-codegen version: 1.14.2

"""
from cian_http.api_client import Api

from . import entities


_api = Api(microservice_name='monolith-cian-profileapi')
promocode_apply = _api.make_client(
    path='/promocode/apply/',
    method='POST',
    handle_http_exceptions=True,
    request_schema=entities.ApplyParameters,
    response_schema=str,
)
v1_sanctions_get_sanctions = _api.make_client(
    path='/v1/sanctions/get-sanctions/',
    method='GET',
    handle_http_exceptions=True,
    request_schema=entities.V1SanctionsGetSanctions,
    response_schema=entities.GetSanctionsResponse,
)
