# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-profileapi`

cian-codegen version: 1.7.1

"""
from cian_http.api_client import Api

from . import entities


_api = Api(microservice_name='monolith-cian-profileapi')
promocode_apply = _api.make_client(
    path='/promocode/apply/',
    method='POST',
    handle_http_exceptions=True,
    request_schema=entities.ApplyParameters,
    response_schema=str,
    default_timeout=10
)
